proxy-providers:
  LIAN:
    type: http
    # è¿™é‡Œå¡«proxy-provider-converterè½¬æ¢å¾—åˆ°çš„é“¾æ¥
    url: "xxxx"
    interval: 3600
    # è¿™é‡Œä¹Ÿæ ¹æ®proxy-provider-converterå¡«å†™
    path: ./api.nxtlnodes.com.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

# ä½¿ç”¨æ··åˆç«¯å£
mixed-port: 7890
# éƒ¨ç½²åœ¨å…¬ç½‘ï¼Œå…³é—­lan
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
ipv6: false
hosts:
  services.googleapis.cn: 216.58.200.67
  www.google.cn: 216.58.200.67
# å¤–éƒ¨ç®¡ç†IPå’Œç«¯å£
external-controller: 0.0.0.0:9090
# å¤–éƒ¨ç®¡ç†å¯†ç 
# secret: 'aafe1234'
clash-for-android:
  append-system-dns: false
profile:
  tracing: true
dns:
  enable: true
  listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
    - 114.114.114.114
    - 180.76.76.76
    - 1.2.4.8
    - 8.8.8.8
    - 4.2.2.1
    - 4.2.2.2
  ipv6: false
  enhanced-mode: fake-ip
  # ä½¿ç”¨æœ¬åœ°hostsæ–‡ä»¶
  use-hosts: true
  # å›½å†…ç”¨ä¸‹åˆ—DNSè§£æ
  nameserver:
    - https://rubyfish.cn/dns-query
    - udp://223.5.5.5
    - udp://180.76.76.76
    - udp://1.2.4.8
    - udp://210.2.4.8
    - tcp://114.114.114.114
    - tls://1.12.12.12
    - tls://120.53.53.53
    - tls://dns.alidns.com
    - tls://dot.pub
    - tls://dot.360.cn
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://doh.360.cn/dns-query
    # ipv6çš„DNS
    # - "[2400:3200::1]:53"
    # - "[2400:3200:baba::1]:53"
    # - https://2400:3200::1/dns-query
    # - https://2400:3200:baba::1/dns-query
    # - "[2402:4e00::]:53"
    # - "[2400:da00::6666]:53"
    # - "[2001:dc7:1000::1]:53"
    # - "[240C::6666]:53"
    # - "[240C::6644]:53"
    # - tls://dns.ipv6dns.com
    # - https://dns.ipv6dns.com/dns-query
    # - "[2001:cc0:2fff:1::6666]:53"
    # - "[2001:cc0:2fff:2::6]:53"
    # - "[2001:da8::666]:53"
    # - "[2001:da8:8000:1:202:120:2:101]:53"
    # - "[2001:da8:202:10::36]:53"
    # - "[2001:da8:202:10::37]:53"
    # - "[2001:da8:208:10::6]:53"
    # - "[2001:da8::666]:53"
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net
  fallback:
    - tls://dns.google
    - tls://dns.adguard.com
    - tls://dns-family.adguard.com
    - tls://dot.sb
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tls://one.one.one.one
    - https://dns.google/dns-query
    - https://dns.google/resolve
    - https://dns.quad9.net/dns-query
    - https://doh.opendns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.dns.sb/dns-query
    - https://doh.sb/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://doh-jp.blahdns.com/dns-query
    # å¸¦å®¶åº­ä¿æŠ¤æˆ–è€…å®‰å…¨çš„DNS
    # - tls://dns.cleanbrowsing.org
    # - https://dns11.quad9.net/dns-query
    # - https://doh.familyshield.opendns.com/dns-query
    # - https://dns-family.adguard.com/dns-query
    # - https://doh.cleanbrowsing.org/doh/family-filter/
      # ipv6çš„DNS
    # - https://[2001:4860:4860::64]/dns-query
    # - https://[2001:4860:4860::6464]/dns-query
    # - https://[2606:4700:4700::1111]/dns-query
    # - https://[2606:4700:4700::1001]/dns-query
    # - https://[2606:4700:4700::64]/dns-query
    # - https://[2606:4700:4700::6464]/dns-query
    # - https://dns.quad9.net/dns-query
    # - https://dns11.quad9.net/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/32
      - 127.0.0.1/32
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.168.0.0/16
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
      - "+.githubusercontent.com"
      - "+.googlevideo.com"     

proxy-groups:
    - { name: 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', type: url-test, url: 'http://www.gstatic.com/generate_204', interval: 300, tolerance: 50, use: ['LIAN'] }
    - { name: 'ğŸ§® ChatGPT', type: select, use: ['LIAN'], proxies: ['â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', type: select, use: ['LIAN'], proxies: ['â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸ“² ç”µæŠ¥æ¶ˆæ¯', type: select, use: ['LIAN'], proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸ“¹ æ²¹ç®¡è§†é¢‘', type: select, use: ['LIAN'], proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸ¥ å¥ˆé£è§†é¢‘', type: select, use: ['LIAN'], proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸ“º å·´å“ˆå§†ç‰¹', type: select, use: ['LIAN'], proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸ“º å“”å“©å“”å“©', type: select, use: ['LIAN'], proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸŒ å›½å¤–åª’ä½“', type: select, use: ['LIAN'], proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'ğŸŒ å›½å†…åª’ä½“', type: select, use: ['LIAN'], proxies: [DIRECT, 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©'] }
    - { name: 'ğŸ“¢ è°·æ­ŒFCM', type: select, use: ['LIAN'], proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©', DIRECT] }
    - { name: 'â“‚ï¸ å¾®è½¯äº‘ç›˜', type: select, use: ['LIAN'], proxies: [DIRECT, 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©'] }
    - { name: 'â“‚ï¸ å¾®è½¯æœåŠ¡', type: select, use: ['LIAN'], proxies: [DIRECT, 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©'] }
    - { name: 'ğŸ è‹¹æœæœåŠ¡', type: select, use: ['LIAN'], proxies: [DIRECT, 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©'] }
    - { name: 'ğŸ® æ¸¸æˆå¹³å°', type: select, use: ['LIAN'], proxies: [DIRECT, 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©'] }
    - { name: 'ğŸ¶ ç½‘æ˜“éŸ³ä¹', type: select, use: ['LIAN'], proxies: [DIRECT, 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©'] }
    - { name: 'ğŸ¯ å…¨çƒç›´è¿', type: select, use: ['LIAN'], proxies: [DIRECT, 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ è‡ªåŠ¨é€‰æ‹©'] }
    - { name: 'ğŸƒ åº”ç”¨å‡€åŒ–', type: select, use: ['LIAN'], proxies: [REJECT, DIRECT] }
    - { name: 'ğŸ›‘ å¹¿å‘Šæ‹¦æˆª', type: select, use: ['LIAN'], proxies: [REJECT, DIRECT, 'ğŸ¯ å…¨çƒç›´è¿'] }
    - { name: 'ğŸ›‘ å…¨çƒæ‹¦æˆª', type: select, use: ['LIAN'], proxies: ['REJECT'] }
    - { name: 'ğŸŸ æ¼ç½‘ä¹‹é±¼', type: select, use: ['LIAN'], proxies: ['ğŸ¯ å…¨çƒç›´è¿', 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', DIRECT] }

rules:
  - 'RULE-SET,Reject,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª'
  - 'RULE-SET,Direct,ğŸ¯ å…¨çƒç›´è¿'
  - 'RULE-SET,OpenAI,ğŸ§® ChatGPT'
  - 'DOMAIN-SUFFIX,poe.com,ğŸ§® ChatGPT'
  - 'RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡'
  - 'RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡'
  - 'RULE-SET,PayPal,ğŸ® æ¸¸æˆå¹³å°'
  - 'RULE-SET,Game,ğŸ® æ¸¸æˆå¹³å°'
  - 'RULE-SET,GlobalMedia,ğŸŒ å›½å¤–åª’ä½“'
  - 'RULE-SET,MainlandMedia,ğŸŒ å›½å†…åª’ä½“'
  - 'RULE-SET,PROXY,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'RULE-SET,SpeedTest,ğŸ¯ å…¨çƒç›´è¿'
  - 'RULE-SET,Domestic,ğŸŒ å›½å†…åª’ä½“'
  - 'GEOIP,CN,ğŸŒ å›½å†…åª’ä½“'
  - 'MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼'
  
  # è‡ªå®šä¹‰éƒ¨åˆ†
  - 'DOMAIN-SUFFIX,mangabz.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,tailscale.com,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,mikanani.me,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,manhuagui.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,mxwljsq.top,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,dmhy.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,fanart.tv,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,telegram.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,sonarr.tv,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,themoviedb.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,opensubtitles.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-KEYWORD,tmdb,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-KEYWORD,themoviedb,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-KEYWORD,telegram,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'

  # BT,PT è§„åˆ™
  - 'DOMAIN-KEYWORD,tracker,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,announce.php?passkey=,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,torrent,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,peer_id=,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,info_hash,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,get_peers,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,find_node,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,BitTorrent,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-KEYWORD,announce_peer,ğŸ¯ å…¨çƒç›´è¿'

  # PTç«™
  - 'DOMAIN-SUFFIX,p2pelite.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  - 'DOMAIN-SUFFIX,edu.cn,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,jpopsuki.eu,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,beitai.pt,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,soulvoice.club,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,nicept.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,tjupt.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,nanyangpt.com,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,skyeysnow.com,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,byr.pt,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,pthome.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,pterclub.com,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,dicmusic.club,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,et8.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,btschool.club,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,keepfrds.com,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,totheglory.im,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,ourbits.club,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,open.cd,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,springsunday.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdsky.me,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hd4fans.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,m-team.cc,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdchina.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,lemonhd.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,pttime.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,upxin.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdhome.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdbd.us,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,eastgame.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,filelist.io,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,chdbits.co,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,gazellegames.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,discfan.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,ccfbits.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,orpheus.network,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,beyond-hd.me,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,avistaz.to,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,cinemaz.to,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,exoticaz.to,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,privatehd.to,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,htpt.cc,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,ptsbao.club,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdatmos.club,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,greatposterwall.com,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdpost.top,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdcity.city,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,shadowthein.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,torrentleech.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hd-space.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hares.top,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdfans.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,msg.vg,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,audiences.me,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,haidan.video,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdtime.org,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hdarea.co,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,carpt.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,gainbound.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,hddolby.com,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,azusa.ru,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,wintersakura.net,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,leaves.red,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,piggo.me,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,monikadesign.uk,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,animetorrents.me,ğŸ¯ å…¨çƒç›´è¿'
  - 'DOMAIN-SUFFIX,iptorrents.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©'
  
rule-providers:
  OpenAI:
    behavior: classical
    interval: 86400
    path: ./Rules/OpenAI.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/OpenAI.yaml'
  Direct:
    behavior: classical
    interval: 86400
    path: ./Rules/Direct.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Direct.yaml'
  Domestic:
    behavior: classical
    interval: 86400
    path: ./Rules/Domestic.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Domestic.yaml'
  Game:
    behavior: classical
    interval: 86400
    path: ./Rules/Game.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Game.yaml'
  GlobalMedia:
    behavior: classical
    interval: 86400
    path: ./Rules/GlobalMedia.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/GlobalMedia.yaml'
  MainlandMedia:
    behavior: classical
    interval: 86400
    path: ./Rules/MainlandMedia.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/MainlandMedia.yaml'
  PROXY:
    behavior: classical
    interval: 86400
    path: ./Rules/Proxy.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Proxy.yaml'
  Reject:
    behavior: classical
    interval: 86400
    path: ./Rules/Reject.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Reject.yaml'
  Apple:
    behavior: classical
    interval: 86400
    path: ./Rules/Apple.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Apple.yaml'
  Microsoft:
    behavior: classical
    interval: 86400
    path: ./Rules/Microsoft.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Microsoft.yaml'
  PayPal:
    behavior: classical
    interval: 86400
    path: ./Rules/PayPal.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/PayPal.yaml'
  SpeedTest:
    behavior: classical
    interval: 86400
    path: ./Rules/SpeedTest.yaml
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/SpeedTest.yaml'